server:
  port: 8848

spring:
  application:
    name: webFlux-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
    loadbalancer:
      ribbon:
        enabled: false
      cache:
        ttl: 30s
        capacity: 256
    circuitbreaker:
      hystrix:
        enabled: true