server:
  port: 8080
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  application:
    name: webFlux-provider
  data:
    mongodb:
      host: localhost
      port: 27017
      database: fluxDB
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true