server:
  port: 8080
  shutdown: graceful

spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: 30s
        max-idle: 8
        min-idle: 0
  lifecycle:
    timeout-per-shutdown-phase: 20s
  application:
    name: webFlux-provider
  data:
    mongodb:
      host: localhost
      port: 27017
      database: fluxDB
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
  r2dbc:
    url: r2dbc:pool:mysql://127.0.0.1:3306/demodb
    username: root
    password: root